apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harswebapp
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/harshalchikhale13/EKS_ArgoCD_Hands-on.git
    path: prod

