apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hweb
  name: hweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hweb
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        resources: {}
status: {}
