apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hweb
    app.kubernetes.io/instance: myargoapp
  name: hweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hweb
  type: Loadbalancer
status:
  loadBalancer: {}
