apiVersion: v1
kind: Service
metadata:
  labels:
    app: hweb
    app.kubernetes.io/instance: myargoapp
  name: hweb
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hweb
  type: LoadBalancer

